version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: idp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yato@5531
      POSTGRES_DB: idp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: idp_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - idp-network
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: idp_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_EMAIL=admin@idp.local
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - idp-network
    depends_on:
      - prometheus

  backend:
    image: backend:latest
    container_name: idp_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/idp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yato@5531
      PROMETHEUS_URL: http://prometheus:9090
      JWT_SECRET: very-secret-key-very-secret-key-very-secret-key-extend-this-key-in-production-for-better-security
    networks:
      - idp-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  idp-network:
    driver: bridge
